### ISSUE TITLE
keyboard visibility breaks with integration of local_auth

### ISSUE THREAD

**Issue by viktor-morin** [MisterJimson/flutter_keyboard_visibility#15]
See following issue, same issue using this package

[https://github.com/adee42/flutter_keyboard_visibility/issues/61](https://github.com/adee42/flutter_keyboard_visibility/issues/61)

**Comment by MisterJimson** [comment]
Thanks for the report. I believe its a side effect of the way this plugin was originally coded.

I've just done the Flutter 1.12 Android plugin migration on the 3.0.0 branch. Would you be willing to see if that branch fixes your issue?

You should be able to depend on that branch by doing

```
flutter_keyboard_visibility:
    git:
      url: git://github.com/MisterJimson/flutter_keyboard_visibility.git
      ref: 3.0.0
```
