### ISSUE TITLE
Failure building app for AndroidX

### ISSUE THREAD

**Issue by aimanuslim** [MisterJimson/flutter_keyboard_visibility#42]
Hi I was trying to build an app that worked otherwise perfectly with the debug version but stumble upon an error relating to androidX. My project is androidx ready as show in gradle properties. Here are the error message:

```

PS D:\codes\nhapp> flutter build apk       
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':url_launcher:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\ScriptKiddie\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\ScriptKiddie\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      20.2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_keyboard_visibility...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    7.3s

D:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
D:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java:25: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
                                  ^
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
D:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java:50: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
                                    ^
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
D:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java:55: error: cannot find symbol
  public void onAttachedToActivity(@NonNull ActivityPluginBinding binding) {
                                    ^
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
D:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java:65: error: cannot find symbol
  public void onReattachedToActivityForConfigChanges(@NonNull ActivityPluginBinding binding) {
                                                      ^
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s


The plugin flutter_keyboard_visibility could not be built due to the issue above.
```

**Comment by MisterJimson** [comment]
Strange that we see `Execution failed for task ':url_launcher:verifyReleaseResources'.` but also the errors related to `flutter_keyboard_visibility`.

Is it possible to get an example project that reproduces this? We have a lot of apps that use AndroidX and all are working alright currently.

**Comment by aimanuslim** [comment]
I am not exactly sure how I can get that example for you. Does `Execution failed for task ':url_launcher:verifyReleaseResources'.` got anything to do with the url launcher package? I do have url_launcher as one of my dependencies for my pubspec.yaml. See below for the full list:

```
....
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  url_launcher: ^4.0.1
  flutter_speed_dial: ^1.2.5
  liquid_pull_to_refresh: ^1.1.1
  flutter_spinkit: "^4.1.1"
  path_provider: ^1.6.0
  carousel_slider: ^1.3.0
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.4 
  random_string: ^2.0.1
  http: ^0.12.0
  sqflite: any
  unicode: ^0.1.0
  intl: ^0.16.0
  numberpicker: ^1.1.0
  flutter_form_builder: ^3.14.1
  flutter_chips_input: ^1.9.4
  provider: ^3.2.0
  grouped_buttons: ^1.0.4
  flutter_plugin_android_lifecycle: 1.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

```
