### ISSUE TITLE
Windows, macOS, and Linux Support

### ISSUE THREAD

**Issue by jhancock4d** [MisterJimson/flutter_keyboard_visibility#87]
**Is your feature request related to a problem? Please describe.**
Right now, this is the only plugin that is blocking us from release for desktop. Please consider adding support for windows, linux and macOS.

**Describe the solution you'd like**
macOS and Linux should just return false as they don't have real touch support natively, and windows should handle the soft keyboard.

**Comment by cbenhagen** [comment]
I added a PR with desktop implementations which return false. If you want to use them before the PR is merged you can do so by adding the following to your `pubspec.yaml`:

```yaml
  flutter_keyboard_visibility_linux:
    git:
      url: https://github.com/cbenhagen/flutter_keyboard_visibility/
      ref: desktop
      path: flutter_keyboard_visibility_linux
  flutter_keyboard_visibility_macos:
    git:
      url: https://github.com/cbenhagen/flutter_keyboard_visibility/
      ref: desktop
      path: flutter_keyboard_visibility_macos
  flutter_keyboard_visibility_windows:
    git:
      url: https://github.com/cbenhagen/flutter_keyboard_visibility/
      ref: desktop
      path: flutter_keyboard_visibility_windows
```
